services:
  php-fpm:
    image: pplulee/sidetp:latest
    container_name: appleautopro-php
    volumes:
      - ./web:/var/www/html
      - .env:/var/www/html/.env
      - ./data/entrypoint.sh:/entrypoint.sh
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - appleautopro-network
    restart: always

  nginx:
    image: nginx:latest
    container_name: appleautopro-nginx
    ports:
      - "127.0.0.1:${WEB_PORT}:80"
    volumes:
      - ./data/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - appleautopro-network
    restart: always

  redis:
    image: redis:latest
    container_name: appleautopro-redis
    volumes:
      - ./data/redis:/data
    networks:
      - appleautopro-network
    restart: always

  mariadb:
    image: mariadb:latest
    container_name: appleautopro-mariadb
    env_file:
      - .env
    volumes:
      - ./data/mariadb/data:/var/lib/mysql
      - ./data/mariadb/conf:/etc/mysql/conf.d
    networks:
      - appleautopro-network
    restart: always
    healthcheck:
      test: [ "CMD", "mariadb-admin", "-h", "localhost", "-u${MARIADB_USER}", "-p${MARIADB_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  backend:
    image: pplulee/appleautopro:v4
    container_name: appleautopro-backend
    depends_on:
      - php-fpm
    networks:
      - appleautopro-network
    restart: always
    deploy:
      replicas: ${BACKEND_THREADS}

networks:
  appleautopro-network:
    driver: bridge
